config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  root 'articles#index'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    mount_uploader :picture, PictureUploader
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article 
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:name, :description, :picture, category_ids: [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @articles = @category.articles
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font italic">
                        by <%= article.user.email if article.user %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.name, article_path(article.id), class: "text-success" %></h5>
                        <p><%= image_tag article.picture_url(:thumb) if article.picture.present? %></p>
                        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                        <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                    </div>
                    <div>
                        <p>
                        <% if article.categories.any? %>
                        <div class="mt-2"><%= render article.categories %></div> 
                        <% end %>
                        </p>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                        edited <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
    <div class="col-10">
        <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description %>
        </div>

        <div class="field">
          <%= f.label :picture %>
          <%= f.file_field :picture %>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "col-3 btn btn-outline-light btn-lg justify-content-center" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <div align="center">
        <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div> 

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<%= render 'article' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.name %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.email if @article.user %>
        </div>
        <div class="card-body">
          <p>
            <%= image_tag(@article.picture_url, width: 300) if @article.picture.present? %>
          </p>
          <div id="card-left"><%= simple_format(@article.description) %></div>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div>
          <p>
            <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div> 
            <% end %>
          </p>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %> 

app/views/categories/_form.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<div class="container">

<div class="row justify-content-center">

<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field justify-content-center">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions justify-content-center">
    <%= form.submit %>
  </div>
<% end %>

</div>

</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="container">
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category.id), class: "text-success" %></h5>
                        <%= link_to "View", category_path(category), class: "btn btn-outline-success" %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(category.created_at) %> ago,
                        edited <%= time_ago_in_words(category.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article' %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
    <small>Copyright &copy; <a><%= link_to "Joshua Retallick", "https://github.com/joshuaretallick/cv", class: "text-white" %></a></small>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">Blog Tech Test</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/articles">Articles</a>
        </li>
        <li class="nav-item">
          <%= link_to 'New Article', new_article_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Create new category', new_category_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to 'View categories', categories_path, class: "nav-link" %>
        </li>
      </ul>
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggingTechTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>